#!/bin/bash

echo "Interface Node: C#"
thrift -r -out src/lib/Generated/ -strict --gen csharp src/thriftfiles/interface-node.thrift

echo "Report Node: C#"
thrift -r -out src/lib/Generated/ -strict --gen csharp src/thriftfiles/report-node.thrift
